# Generated by Django 5.2.16 on 2026-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapi_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("director", models.CharField(max_length=255)),
                ("producer", models.CharField(max_length=255)),
                ("episode_id", models.PositiveIntegerField()),
                ("opening_crawl", models.TextField()),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapi_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("height", models.PositiveIntegerField()),
                ("mass", models.PositiveIntegerField()),
                ("hair_color", models.CharField(max_length=255)),
                ("skin_color", models.CharField(max_length=255)),
                ("eye_color", models.CharField(max_length=255)),
                ("birth_year", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="swapi.film"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Starship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swapi_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("cost_in_credits", models.BigIntegerField(blank=True, null=True)),
                ("length", models.PositiveIntegerField(blank=True, null=True)),
                ("manufacturer", models.CharField(max_length=255)),
                ("crew", models.CharField(max_length=100)),
                ("passengers", models.CharField(max_length=100)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="starships", to="swapi.film"
                    ),
                ),
            ],
        ),
    ]
