# Generated by Django 5.2.16 on 2026-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="mass",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
