# Generated by Django 5.2.16 on 2026-07-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swapi", "0002_alter_character_height_alter_character_mass"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="film",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="starship",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
