# Generated by Django 5.2.16 on 2026-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swapi", "0003_character_votes_film_votes_starship_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starship",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
